[package]
name = "clausy"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.8.5"
pest_derive = "2.8.5"
tempfile = "3.24.0"
num = "0.4.3"
clap = { version = "4.5.56", features = ["derive"] }
